### ISSUE TITLE
Link to Pivotal Tracker does not work

### ISSUE THREAD

**Issue by flowonyx** [thechangelog/infrastructure#2]
The links to "Pivotal Tracker" (https://www.pivotaltracker.com/n/projects/1650121) and "wiki" both say that the project cannot be found. It may be a private project.

**Comment by gerhard** [comment]
Yes, that's right, the project is private. Why are you interested in Pivotal Tracker access?

@jerodsanto we could either remove the link, since the project is not public, or we could make it world-readable. I am leaning towards removing the link, but let me know your thoughts.

**Comment by flowonyx** [comment]
I was just trying to get a feel for the project and the README says that is where to look if you want to understand **why** things are the way they are. It just curiosity, so I don't need access, but I thought you might want to either make it public or remove the link from the README, so I was mostly just letting you know.

**Comment by gerhard** [comment]
For your last answer alone I would be happy to share _the way sausage is made_ at changelog.com 😉 

We need to reach consensus with @jerodsanto before we action this either way, will update when we know more. 💚

**Comment by jerodsanto** [comment]
I don't feel comfortable making that pivotal tracker project open, because I am not sure whether or not there is personal/private content in there that I'm not thinking of. Let's remove the link.

**Comment by gerhard** [comment]
@flowonyx hope that the blog post which I'm putting together for the 2019 infrastructure will have some of the insights that you were looking for here. An overview of what I'll be covering:

![infrastructure](https://user-images.githubusercontent.com/3342/52139725-d6843480-2648-11e9-8042-11570fe9eaf4.png)
